color: null
description: null
fieldLayouts:
  e5072735-a18d-430e-a3cf-b37da0193890:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-12T11:14:02+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 22881516-a425-4dcf-827d-11def889a426
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-12T11:16:49+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7fd8bc53-fb22-4c72-a07b-c7b695e5facb # Link
            handle: navLink
            includeInCards: false
            instructions: null
            label: Link
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72930be1-62b0-4097-8710-77455192e2e9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2dded080-a86e-4ab6-8fa3-f659cbb1da99
        userCondition: null
handle: navigatieItem
hasTitleField: true
icon: null
name: 'Navigatie item'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
