color: null
description: null
fieldLayouts:
  ee326f40-21af-4e6f-98a8-8093825eb613:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-12T15:29:40+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2f0a0250-37e7-46fd-af0c-aac0b4c67853
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-12T15:31:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a283a7f9-9cff-4714-a573-af42f5ecdfa2 # Korte Beschrijving Visie
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 049d86e2-c9e1-4102-ab91-f4b71832e9e9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-12T15:31:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: adb59983-1f59-4105-9b31-ab9ddcb2bf92 # Volledige Text van de pagina
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 706a1e65-9298-484d-aab7-7c190bd83889
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 44eaf9c8-ce5c-4741-9e36-d41f5c484cdf
        userCondition: null
handle: opdrachtsverklaringentry
hasTitleField: true
icon: null
name: OpdrachtsverklaringEntry
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
