color: cyan
description: 'Voeg hier je projecten aan toe'
fieldLayouts:
  42030eba-7928-4b6b-b82f-8a92f8ff5d32:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-19T09:02:42+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 47d46543-14d1-4f21-a25f-909d64f11f9b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-19T09:07:40+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 438e2ad8-8996-4c38-b800-36d0836f06b6 # Project Logo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c7c8255-8112-461e-abc5-b2cff02660ec
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-19T09:10:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cb6a08e3-c0d3-4915-b329-c8c612b61289 # Project Korte Uitleg
            handle: null
            includeInCards: false
            instructions: 'Voeg hier je korte uitleg van je project aan toe'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af72ceb6-20f0-41ba-8bd4-c82a418b7269
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-19T09:07:40+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f409a2ce-b0be-4686-b8ed-1e6c75b246f4 # Project Uitleg
            handle: projectVolledigeUitleg
            includeInCards: false
            instructions: 'Voeg hier je volledige uitleg van je project aan toe'
            label: 'Project Volledige Uitleg'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2bde7d35-0ec9-4eef-a75b-35dae2c9140b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1e1c6ecd-0b0d-42bd-8194-fb95b0ef7ce7
        userCondition: null
handle: projecten
hasTitleField: true
icon: bullseye-arrow
name: Projecten
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
