color: blue
description: 'Voeg hier een vacature toe zoals die gepubliceerd wordt op de website of VDAB.'
fieldLayouts:
  95f4e154-4902-4927-af6d-f85c4517139e:
    cardThumbAlignment: end
    cardView:
      - uri
      - slug
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-08T19:54:39+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0d6eb5af-6148-4147-b981-1e64f9233209
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-08T19:49:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d1df8b1e-5f4a-4e3c-b535-615a3372a2a2 # Functie
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 116203ea-8703-4708-bc92-89737fe4c209
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-08T19:49:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e9d9ed4b-05f3-487a-a727-c3217546dc7e # Contact Persoon Vacature
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62a4ba18-f384-45b5-8831-d54e7b14876e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-08T19:49:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b91fc340-8606-4546-a404-7e74d51a9d74 # Externe Link Vacature
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 070a91a6-f593-4614-ac5f-fdab2e92e885
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-08T19:49:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9e7e2739-6927-48cb-8555-72302fed359f # Korte Beschrijving Vacature
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 527cd09c-e7fb-4546-a12d-660c1329cf13
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-08T19:49:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f9c980ce-ffb1-492b-8828-a605e53046be # Volledige Omschrijving Vacature
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89f2577b-f781-418e-8032-e5ff0ca3b116
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3b5a1ccf-7732-455a-bbdb-bd71a0bbff79
        userCondition: null
handle: vacature
hasTitleField: true
icon: briefcase
name: Vacature
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
