color: null
description: null
fieldLayouts:
  0458d132-65b9-47ae-8ef8-3fca121f70b5:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-12T11:23:39+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d35fa2f6-ac60-4232-bee0-d5e6b933a139
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 703a7303-bb9b-4b28-a6d2-cc64854be69b
        userCondition: null
handle: vacatureIndexpagina
hasTitleField: true
icon: null
name: 'Vacature indexpagina'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
