color: green
description: 'Dit is waar je de inhoud van de pagina "Visie" kan aanpassen.'
fieldLayouts:
  4af7214e-ee9b-4422-acee-259d16793dae:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-12T10:30:48+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 000592c1-2954-49e9-89ce-f1f169fe7f09
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-12T10:37:10+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a283a7f9-9cff-4714-a573-af42f5ecdfa2 # Korte Beschrijving Visie
            handle: shortTextVisie
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5d5f767-be51-4b29-afac-d57e6482b9a1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-12T10:33:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: adb59983-1f59-4105-9b31-ab9ddcb2bf92 # Volledige Text van de pagina
            handle: fullTextVisie
            includeInCards: false
            instructions: 'Dit is de rest van de pagina van "Visie" hier plak je heel de text in'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2977a932-74a6-4e97-b365-d1808d17c46d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9c241440-fe52-47af-a46a-ce05d7a6a9de
        userCondition: null
handle: visieInhoud
hasTitleField: true
icon: eye
name: 'Visie Inhoud'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
