altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  468f9cfc-b8c9-40d6-8ada-ffd355c0657e:
    cardThumbAlignment: end
    cardView:
      - dateCreated
      - imageSize
      - size
      - filename
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-10T18:12:11+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 413cbf1a-74be-45f6-b8cf-55cb6d21d21e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cbfee6a0-5947-4c10-bc8a-30dde1bdc56e
        userCondition: null
fs: localUploads
handle: contentImages
name: 'Content Images'
sortOrder: 12
subpath: content
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
