altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  dd89236d-c51a-4820-9bb1-2019944f63c2:
    cardThumbAlignment: end
    cardView:
      - dateCreated
      - size
      - filename
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-10T18:15:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 99546ac0-5ccb-4819-af43-40bcb2bbf3ed
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 290256a3-3989-4829-b670-aa156ce77bac
        userCondition: null
fs: localUploads
handle: forms
name: Forms
sortOrder: 14
subpath: forms
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
