altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  bd3b43c8-2a4e-4d82-9a40-8417352b1f92:
    cardThumbAlignment: end
    cardView:
      - dateUpdated
      - size
      - filename
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-10T18:12:51+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 3e17ed5e-a3d5-4ed8-9ca3-4fa1189e2337
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 96cbecd3-95a2-474d-bc83-2cf9dc497c8d
        userCondition: null
fs: localUploads
handle: icons
name: 'Icons '
sortOrder: 13
subpath: icons
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
