altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  4065dd80-4ebd-4a86-a54b-281ca3fd8de9:
    cardThumbAlignment: end
    cardView:
      - dateCreated
      - imageSize
      - size
      - filename
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-10T18:08:17+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 688cc71c-3264-4125-a9f2-5a053a8b18bb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fa9a9cc4-1dcd-4bcd-a56d-b942357a69f3
        userCondition: null
fs: localUploads
handle: projectImages
name: 'Project Images'
sortOrder: 8
subpath: projectImages
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
