altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  06a5b84d-6675-404a-95ef-4fcef3e0a22f:
    cardThumbAlignment: end
    cardView:
      - dateCreated
      - size
      - filename
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-10T18:09:37+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 318e9f22-f037-44f3-8cf0-5dceade66056
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 54f859f7-c1ba-4084-9557-f041d06df995
        userCondition: null
fs: localUploads
handle: publicaties
name: Publicaties
sortOrder: 9
subpath: publicaties
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
