altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  f10884c4-0be1-4939-9aa4-44eae007425f:
    cardThumbAlignment: end
    cardView:
      - dateCreated
      - imageSize
      - size
      - filename
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-10T18:05:40+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: e8f0917d-bbc0-4f89-ac6a-4f6ef153ee7d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e7c29d6c-20d5-4676-818c-34a72df3a09b
        userCondition: null
fs: localUploads
handle: serviceImages
name: 'Service Images'
sortOrder: 4
subpath: diensten
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
