altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  636e6176-476c-4ffa-b19b-963144eca6ab:
    cardThumbAlignment: end
    cardView:
      - dateCreated
      - imageSize
      - size
      - filename
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-10T18:06:58+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 3ab1cfd9-46a5-4f0c-8b1d-bad5c8531814
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 463d5221-989e-4d84-843b-c8cb4f15e82c
        userCondition: null
fs: localUploads
handle: staffPhotos
name: 'Staff Photos'
sortOrder: 6
subpath: werknemers
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
