columnSuffix: null
handle: adresContactpagina
instructions: "\tVul hier het volledige adres in van het woonzorgcentrum."
name: 'Adres Contact Pagina'
searchable: false
settings:
  maxAddresses: null
  minAddresses: null
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Addresses
