columnSuffix: null
handle: openingsurenDienst
instructions: 'Geef de standaard openingsuren van deze dienst'
name: 'Openingsuren dienst'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: '“Maandag–vrijdag 14u–17u”'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
