columnSuffix: null
handle: pdfBestand
instructions: 'Upload hier de PDF-versie van de publicatie. Alleen .pdf bestanden zijn toegelaten.'
name: PDF-Bestand
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - audio
    - captionsSubtitles
    - compressed
    - excel
    - image
    - json
    - javascript
    - powerpoint
    - text
    - video
    - word
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:1f2afb75-6a53-471d-877e-4a42c92b3dcb' # Publicaties
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:89276b58-e746-4865-9457-e4f9032bb98c' # Site Logos
  restrictedLocationSubpath: null
  selectionLabel: null
  showCardsInGrid: false
  showSearchInput: true
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:1f2afb75-6a53-471d-877e-4a42c92b3dcb' # Publicaties
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
