columnSuffix: null
handle: prijslijstDienst
instructions: 'Upload hier een PDF met prijslijst, menu of infofiche'
name: 'Prijslijst Dienst'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - pdf
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:f344656f-f92a-4a7f-b55f-74800de51ab5' # Price List
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:89276b58-e746-4865-9457-e4f9032bb98c' # Site Logos
  restrictedLocationSubpath: null
  selectionLabel: null
  showCardsInGrid: false
  showSearchInput: true
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:f344656f-f92a-4a7f-b55f-74800de51ab5' # Price List
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
