columnSuffix: null
handle: publicatieType
instructions: "Selecteer het juiste type (menu, brochure, jaarverslag, …). \r\nAls het type er niet bij staat moet je er eentje aanmaken bij categorieën "
name: 'Publicatie Type'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showCardsInGrid: false
  showSearchInput: true
  showSiteMenu: false
  source: null
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
