columnSuffix: null
handle: volledigeTextVanDePagina
instructions: 'Dit is de rest van de pagina van "Visie" hier plak je heel de text in ( je kan de text ook mooier laten ogen met de editor die je hebt )'
name: 'Volledige Text van de pagina'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  characterLimit: null
  ckeConfig: 28329803-f84b-430a-a39d-a662c4cf2ec2 # Simple
  createButtonLabel: null
  defaultTransform: null
  expandEntryButtons: false
  fullGraphqlData: true
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
