columnSuffix: null
handle: volledigeOmschrijvingVacature
instructions: "\tHier kan je de volledige vacaturetekst plaatsen"
name: 'Volledige Omschrijving Vacature'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
