currLabel: Categories
customIcon: null
enabled: true
handle: categories
icon: sitemap
layout: 6f02beaa-17a0-4a9c-a32d-fbe673c00b5e # Default
level: 1
newWindow: false
parent: null
prevLabel: Categories
prevLevel: 1
prevParent: null
prevUrl: categories
sortOrder: 4
type: craft
url: categories
