currLabel: Globals
customIcon: null
enabled: true
handle: globals
icon: globe
layout: 6f02beaa-17a0-4a9c-a32d-fbe673c00b5e # Default
level: 1
newWindow: false
parent: null
prevLabel: Globals
prevLevel: 1
prevParent: null
prevUrl: globals
sortOrder: 3
type: craft
url: globals
