currLabel: GraphQL
customIcon: null
enabled: true
handle: graphql
icon: graphql
layout: 6f02beaa-17a0-4a9c-a32d-fbe673c00b5e # Default
level: 1
newWindow: false
parent: null
prevLabel: GraphQL
prevLevel: 1
prevParent: null
prevUrl: graphql
sortOrder: 6
type: craft
url: graphql
