currLabel: Settings
customIcon: null
enabled: true
handle: settings
icon: gear
layout: 6f02beaa-17a0-4a9c-a32d-fbe673c00b5e # Default
level: 1
newWindow: false
parent: null
prevLabel: Settings
prevLevel: 1
prevParent: null
prevUrl: settings
sortOrder: 11
type: craft
url: settings
