currLabel: Tokens
customIcon: null
enabled: true
handle: tokens
icon: null
layout: 6f02beaa-17a0-4a9c-a32d-fbe673c00b5e # Default
level: 2
newWindow: false
parent: fee0fdf0-3004-420c-a1d4-c1b0a6d60b8f
prevLabel: Tokens
prevLevel: 2
prevParent: fee0fdf0-3004-420c-a1d4-c1b0a6d60b8f
prevUrl: graphql/tokens
sortOrder: 8
type: craft
url: graphql/tokens
