currLabel: Utilities
customIcon: null
enabled: true
handle: utilities
icon: wrench
layout: 6f02beaa-17a0-4a9c-a32d-fbe673c00b5e # Default
level: 1
newWindow: false
parent: null
prevLabel: Utilities
prevLevel: 1
prevParent: null
prevUrl: utilities
sortOrder: 10
type: craft
url: utilities
