defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 752d68b4-df44-4459-8585-a8ad998a45a6 # Contact Pagina
handle: contact
maxAuthors: 1
name: Contact
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  7a19be51-2e75-477b-b593-bfdf3fd6de08: # Sint Coleta
    enabledByDefault: true
    hasUrls: true
    template: contact/_entry.twig
    uriFormat: contact
type: single
