defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: c54651e8-c41e-43e4-abac-4fe49424d135 # Homepage
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  7a19be51-2e75-477b-b593-bfdf3fd6de08: # Sint Coleta
    enabledByDefault: true
    hasUrls: true
    template: home.twig
    uriFormat: __home__
type: single
