defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: bd1f9264-1ce4-4c60-a579-4e57ada41125 # Projecten
handle: projecten
maxAuthors: 1
name: Projecten
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  7a19be51-2e75-477b-b593-bfdf3fd6de08: # Sint Coleta
    enabledByDefault: true
    hasUrls: true
    template: projecten/_entry.twig
    uriFormat: 'projecten/{slug}'
type: channel
